/*
The purpose of this module is to provide report about all clients' debts.
Also it provides basic search and print button.
*/
// vendor
import React, { Component } from "react";
import { connect } from "react-redux";
import { FormattedMessage, injectIntl } from "react-intl";
import {Input, Button} from 'antd';
import _ from "lodash";

const Search = Input.Search;

// proj
import {
    fetchReportOrders,
    fetchReportOrdersFilterOptions,
    setReportOrdersIncludeServicesDiscount,
    setReportOrdersIncludeAppurtenanciesDiscount,
    setReportOrdersQuery,
    setReportOrdersStatus,
    setReportOrdersCreationFromDate,
    setReportOrdersCreationToDate,
    setReportOrdersAppointmentFromDate,
    setReportOrdersAppointmentToDate,
    setReportOrdersDoneFromDate,
    setReportOrdersDoneToDate,
    setReportOrdersPage,
    setReportOrdersAllFilters
} from 'core/reports/reportOrders/duck';
import { ReportOrdersFilterModal, ReportOrdersExportModal } from 'modals';
import { setModal, resetModal, MODALS } from 'core/modals/duck';

import { Layout, Numeral } from "commons";
import { ReportOrdersTable, ReportOrdersFilter } from "components";
import { isForbidden, permissions } from "utils";

// own
import Styles from "./styles.m.css";
import Stats from './Stats';

const mapStateToProps = state => ({
    tableData: state.reportOrders.tableData,
    includeServicesDiscount: state.reportOrders.options.includeServicesDiscount,
    includeAppurtenanciesDiscount: state.reportOrders.options.includeAppurtenanciesDiscount,
    filter: state.reportOrders.filter,
    page: state.reportOrders.filter.page,
    stats: state.reportOrders.stats,
    filterOptions: state.reportOrders.filterOptions,
    modal: state.modals.modal,
    reportOrdersFetching: state.ui.reportOrdersFetching,
});

const mapDispatchToProps = {
    fetchReportOrders,
    fetchReportOrdersFilterOptions,
    setReportOrdersPage,
    setReportOrdersIncludeServicesDiscount,
    setReportOrdersIncludeAppurtenanciesDiscount,
    setReportOrdersQuery,
    setReportOrdersStatus,
    setReportOrdersCreationFromDate,
    setReportOrdersCreationToDate,
    setReportOrdersAppointmentFromDate,
    setReportOrdersAppointmentToDate,
    setReportOrdersDoneFromDate,
    setReportOrdersDoneToDate,
    setReportOrdersAllFilters,

    setModal,
    resetModal,
};

@connect(
    mapStateToProps,
    mapDispatchToProps,
)
@injectIntl
export default class ReportOrdersPage extends Component {
    constructor(props) {
        super(props);

        this.exportModalFormRef = null;

        this.onOpenFilterModal = this.onOpenFilterModal.bind(this);
        this.onCloseFilterModal = this.onCloseFilterModal.bind(this);
        this.onSubmitFilterModal = this.onSubmitFilterModal.bind(this);

        this.onOpenExportModal = this.onOpenExportModal.bind(this);
        this.onCloseExportModal = this.onCloseExportModal.bind(this);
        this.onSubmitExportModal = this.onSubmitExportModal.bind(this);
        
        this.saveExportModalFormRef = this.saveExportModalFormRef.bind(this);
    }

    componentDidMount() {
        this.props.fetchReportOrders();
        this.props.fetchReportOrdersFilterOptions();
    }

    

    onOpenFilterModal() {
        this.props.setModal(MODALS.REPORT_ORDERS_FILTER);
    }

    onCloseFilterModal() {
        this.props.resetModal();
    }

    onOpenExportModal() {
        this.props.setModal(MODALS.REPORT_ORDERS_EXPORT);
    }

    onCloseExportModal() {
        this.props.resetModal();
    }

    onSubmitExportModal() {
        if(this.exportModalFormRef) {
            const {form} = this.exportModalFormRef.props;

            form.validateFields((err, values) => {
                if (err) {
                  return;
                }
          
                console.log('Received values of form: ', values);
                form.resetFields();
                this.onCloseExportModal();
              });
        }
    }

    saveExportModalFormRef = formRef => {
        this.exportModalFormRef = formRef;
    };

    

    //This method takes filters generated by modal, overrides them in duck and fetch result
    onSubmitFilterModal(filters) {
        const {
            setReportOrdersAllFilters,
            fetchReportOrders,
            resetModal
        } = this.props;
        setReportOrdersAllFilters(filters);
        fetchReportOrders();
        resetModal();
    }

    render() {
        const {
            fetchReportOrders,
            tableData,
            setReportOrdersIncludeServicesDiscount,
            setReportOrdersIncludeAppurtenanciesDiscount,
            includeServicesDiscount,
            includeAppurtenanciesDiscount,
            filter,
            stats,
            setReportOrdersPage,
            filterOptions,
            reportOrdersFetching,

            setReportOrdersQuery,
            setReportOrdersStatus,
            setReportOrdersCreationFromDate,
            setReportOrdersCreationToDate,
            setReportOrdersAppointmentFromDate,
            setReportOrdersAppointmentToDate,
            setReportOrdersDoneFromDate,
            setReportOrdersDoneToDate,

            modal,
        } = this.props;

        //Transfer all filter methods in one object to easily manipulate data
        const filterControls = {
            fetchReportOrders,
            onOpenFilterModal: () => this.onOpenFilterModal(),

            setReportOrdersPage,
            setReportOrdersIncludeServicesDiscount,
            setReportOrdersIncludeAppurtenanciesDiscount,
            includeServicesDiscount,
            includeAppurtenanciesDiscount,

            setReportOrdersQuery,
            setReportOrdersStatus,
            setReportOrdersCreationFromDate,
            setReportOrdersCreationToDate,
            setReportOrdersAppointmentFromDate,
            setReportOrdersAppointmentToDate,
            setReportOrdersDoneFromDate,
            setReportOrdersDoneToDate,
        };
        
        return (
            <Layout
                title={
                    <div>
                        <div><FormattedMessage id="navigation.report_orders" /></div>
                        <div><Button onClick={this.onOpenExportModal}>Export</Button></div>
                    </div>
                }
                paper={false}
            >
                <section>
                    <Stats stats={stats}/>
                </section>

                <ReportOrdersTable
                    stats={stats}
                    filterControls={filterControls}
                    filter={filter}
                    tableData={tableData}
                    setIncludeServicesDiscount={setReportOrdersIncludeServicesDiscount}
                    includeServicesDiscount={includeServicesDiscount}
                    loading={reportOrdersFetching}
                />
                <ReportOrdersFilterModal 
                    visible={modal}
                    filter={filter}
                    onSubmit={this.onSubmitFilterModal}
                    onCloseFilterModal={this.onCloseFilterModal}
                    filterOptions={filterOptions}
                />
                <ReportOrdersExportModal
                    visible={modal}
                    wrappedComponentRef={this.saveExportModalFormRef}
                    onCancel={this.onCloseExportModal}
                    onOk={this.onSubmitExportModal}
                />
            </Layout>
        );
    }
}
