export default Object.freeze({
    FETCH_LOCALE_CONTENT: 'FETCH_LOCALE_CONTENT',
    UPDATE_INTL:          'UPDATE_INTL',
    UPDATE_INTL_SUCCESS:  'UPDATE_INTL_SUCCESS',
    UPDATE_INTL_FAIL:     'UPDATE_INTL_FAIL',
});
