export default Object.freeze({
    SET_LAYOUT_STATE:             'SET_LAYOUT_STATE',
    SET_SWAPI_FETCHING_STATE:     'SET_SWAPI_FETCHING_STATE',
    SET_AUTH_FETCHING_STATE:      'SET_AUTH_FETCHING_STATE',
    SET_ORDERS_FETCHING_STATE:    'SET_ORDERS_FETCHING_STATE',
    SET_MY_TASKS_FETCHING_STATE:  'SET_MY_TASKS_FETCHING_STATE',
    SET_ORDER_FETCHING_STATE:     'SET_ORDER_FETCHING_STATE',
    SET_DASHBOARD_FETCHING_STATE: 'SET_DASHBOARD_FETCHING_STATE',
    // global
    // SET_ONLINE_STATUS:       'SET_ONLINE_STATUS',
    INITIALIZE:                   'INITIALIZE',
    SET_COLLAPSED_STATE:          'SET_COLLAPSED_STATE',
    EMIT_ERROR:                   'EMIT_ERROR',
});
