export default Object.freeze({
    SET_SWAPI_FETCHING_STATE:  'SET_SWAPI_FETCHING_STATE',
    // SET_ONLINE_STATUS:       'SET_ONLINE_STATUS',
    SET_AUTH_FETCHING_STATE:   'SET_AUTH_FETCHING_STATE',
    SET_ORDERS_FETCHING_STATE: 'SET_ORDERS_FETCHING_STATE',
    INITIALIZE:                'INITIALIZE',
    SET_COLLAPSED_STATE:       'SET_COLLAPSED_STATE',
    EMIT_ERROR:                'EMIT_ERROR',
});
