export default Object.freeze({
    // fetchSWAPIs
    FETCH_SWAPI:         'FETCH_SWAPI',
    FETCH_SWAPI_SUCCESS: 'FETCH_SWAPI_SUCCESS',
    FETCH_SWAPI_FAIL:    'FETCH_SWAPI_FAIL',
    //
    // // createSWAPI
    // CREATE_SWAPI:         "CREATE_SWAPI",
    // CREATE_SWAPI_SUCCESS: "CREATE_SWAPI_SUCCESS",
    // CREATE_SWAPI_FAIL:    "CREATE_SWAPI_FAIL",
    //
    // // deleteSWAPI
    // DELETE_SWAPI:         "DELETE_SWAPI",
    // DELETE_SWAPI_SUCCESS: "DELETE_SWAPI_SUCCESS",
    // DELETE_SWAPI_FAIL:    "DELETE_SWAPI_FAIL",
    //
    // // likeSWAPI
    // LIKE_SWAPI:         "LIKE_SWAPI",
    // LIKE_SWAPI_SUCCESS: "LIKE_SWAPI_SUCCESS",
    // LIKE_SWAPI_FAIL:    "LIKE_SWAPI_FAIL",
    //
    // // unlikeSWAPI
    // UNLIKE_SWAPI:         "UNLIKE_SWAPI",
    // UNLIKE_SWAPI_SUCCESS: "UNLIKE_SWAPI_SUCCESS",
    // UNLIKE_SWAPI_FAIL:    "UNLIKE_SWAPI_FAIL",
});
